# Generated by Django 5.1.5 on 2025-02-02 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WallapopSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=255)),
                ('period', models.IntegerField(help_text='Check period in minutes', validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=False)),
                ('last_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallapop Search',
                'verbose_name_plural': 'Wallapop Searches',
            },
        ),
    ]
